### ISSUE TITLE
在登入驗證未過時，用戶仍能夠和前端元件進行互動（輸入值...），但無法如預期行為送出至後端

### ISSUE THREAD

**Issue by JimCHH** [neurobit-ai/eyeForm#1]
登入驗證未過時，仍能夠和前端元件進行互動（輸入值...），但最後無法送出

**Describe the solution you'd like**
登入後才能與元件互動

**Describe alternatives you've considered**
或是提供暗示，引導用戶先登入

**Comment by x1001000** [comment]
https://github.com/neurobit-ai/eyeForm/commit/8e30a1fde439c849dbd1b992a1915344d3fb7c88
