### ISSUE TITLE
Fix code scanning alert - DOM text reinterpreted as HTML

### ISSUE THREAD

**Issue by JimCHH** [neurobit-ai/eyeForm#2]
Tracking issue for:
- [x] https://github.com/neurobit-ai/eyeForm/security/code-scanning/1

**Comment by x1001000** [comment]
6cd975b80d509f265e8276b294da91aef3ae6571

**Comment by JimCHH** [comment]
> [6cd975b](https://github.com/neurobit-ai/eyeForm/commit/6cd975b80d509f265e8276b294da91aef3ae6571)

這是 source code 本身的問題嗎？

**Comment by x1001000** [comment]
看似 [demo.html](https://github.com/neurobit-ai/eyeForm/blob/88b3d1e0c0c6540483bf83ac97c27696845792df/fonts/icomoon/Read%20Me.txt) 有個顯示 code 的 debug 功能，被你的弱掃工具 alert 了，不要放進 production 就好，其實也沒用到多少 [template](https://colorlib.com/wp/template/contact-form-v5/) 的 source code，主要是用 [Bootstrap](https://getbootstrap.com/)的 example 和 [Google](https://developers.google.com/identity/gsi/web/guides/display-button) 的 guide 去實作

**Comment by x1001000** [comment]
看似 [template](https://colorlib.com/wp/template/contact-form-v5/) 中有個[把 code 本身顯示在網頁文字的 develop/debug/demo 功能](https://github.com/neurobit-ai/eyeForm/blob/88b3d1e0c0c6540483bf83ac97c27696845792df/fonts/icomoon/Read%20Me.txt)，被你的弱掃工具 alert 了，不要放進 production 就好，其實也沒用到多少 template 的 source code 了，主要是用 [Bootstrap](https://getbootstrap.com/docs/5.2/forms/overview/) 的 example 和 [Google](https://developers.google.com/identity/gsi/web/guides/display-button) 的 guide 去實作
